
package Lab2;

import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
* Class          Loan Calculator
* File           LoanCalculator.java
* Description    Calculates monthly payment given
*                loan amount, interest, and years of loan
* @author        Caitlin McMurchie
* Environment    PC, Windows 10, jdk 1.8.0_151, NetBeans 8.2
* Date           1/8/2018
* @version       1.0.0
* @see           java.io
* @see           javax.swing.JFrame
* History Log    
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/ 
public class LoanCalculator extends javax.swing.JFrame {
        int counter =0; //class level variable for counter
    /**
     * Default Constructor Creates new form LoanCalculator
     */
    public LoanCalculator() {
        initComponents();
        this.setLocationRelativeTo(null);   //centers form
        this.getRootPane().setDefaultButton(CalculateJButton);
        
        // set icon for form
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("\\\\zeus\\profile$\\955331307\\my documents\\CS 141\\Lab 2\\Lab 2 -- Loan Calculator\\eclipse.png"));
        PrincipalJTextField.requestFocus();
        setDate();
    }
    //Needs JavaDocs
    private void setDate()
    {   
        DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
        Date date = new Date();
        this.setTitle("Loan Calculator--" + dateFormat.format(date));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        CounterJLabel = new javax.swing.JLabel();
        CounterJTextField = new javax.swing.JTextField();
        PrincipalLabel = new javax.swing.JLabel();
        PrincipalJTextField = new javax.swing.JTextField();
        RateJLabel = new javax.swing.JLabel();
        RateJTextField = new javax.swing.JTextField();
        YearsJLabel = new javax.swing.JLabel();
        YearsJTextField = new javax.swing.JTextField();
        CalculateJButton = new javax.swing.JButton();
        PaymentJTextField = new javax.swing.JTextField();
        InterestJLabel = new javax.swing.JLabel();
        InterestJTextField = new javax.swing.JTextField();
        ClearJButton = new javax.swing.JButton();
        QuitJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lab 2 -- Loan Calculator");
        setBackground(new java.awt.Color(255, 204, 255));
        setPreferredSize(new java.awt.Dimension(393, 293));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(7, 2, 3, 3));

        CounterJLabel.setBackground(new java.awt.Color(255, 204, 255));
        CounterJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CounterJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CounterJLabel.setText("Calculation Counter:");
        getContentPane().add(CounterJLabel);

        CounterJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CounterJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        CounterJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CounterJTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(CounterJTextField);

        PrincipalLabel.setBackground(new java.awt.Color(255, 204, 255));
        PrincipalLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PrincipalLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PrincipalLabel.setText("Loan Amount:");
        getContentPane().add(PrincipalLabel);

        PrincipalJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PrincipalJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(PrincipalJTextField);

        RateJLabel.setBackground(new java.awt.Color(255, 204, 255));
        RateJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RateJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        RateJLabel.setText("Interest Rate (as %):");
        getContentPane().add(RateJLabel);

        RateJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RateJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        RateJTextField.setToolTipText("Intrest rate as percent without percent sign, e.g 4.9 NOT 4.9%");
        getContentPane().add(RateJTextField);

        YearsJLabel.setBackground(new java.awt.Color(255, 204, 255));
        YearsJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        YearsJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        YearsJLabel.setText("Years:");
        getContentPane().add(YearsJLabel);

        YearsJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        YearsJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(YearsJTextField);

        CalculateJButton.setBackground(new java.awt.Color(255, 204, 204));
        CalculateJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CalculateJButton.setMnemonic('c');
        CalculateJButton.setText("Calculate Payment");
        CalculateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CalculateJButton);

        PaymentJTextField.setEditable(false);
        PaymentJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PaymentJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(PaymentJTextField);

        InterestJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        InterestJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        InterestJLabel.setText("Interest");
        getContentPane().add(InterestJLabel);

        InterestJTextField.setEditable(false);
        InterestJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        InterestJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        InterestJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InterestJTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(InterestJTextField);

        ClearJButton.setBackground(new java.awt.Color(255, 204, 204));
        ClearJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ClearJButton.setMnemonic('l');
        ClearJButton.setText("Clear");
        ClearJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ClearJButton);

        QuitJButton.setBackground(new java.awt.Color(255, 204, 204));
        QuitJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        QuitJButton.setMnemonic('q');
        QuitJButton.setText("Quit");
        QuitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(QuitJButton);

        pack();
    }// </editor-fold>                        

    private void InterestJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void QuitJButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // Ends the application
        System.exit(0);
    }                                           

    private void ClearJButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // Clears all text
        CounterJTextField.setText(" ");
        InterestJTextField.setText(" ");
        PrincipalJTextField.setText(" ");
        YearsJTextField.setText(" ");
        PaymentJTextField.setText(" ");
        InterestJTextField.setText(" ");
        RateJTextField.setText(" ");
    }                                            

    private void CounterJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 
//Needs LOTS of JavaDocs
    private void CalculateJButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // read the inputs and calculate payment of loan
        //constants for max values, and number of comoundings per year
        final double MAX_AMOUNT = 100000000;
        final double MAX_INTEREST_RATE = 100;
        final int COUMPOUNDINGS = 12;
        final double MAX_YEARS = 50;
        final double PERIOD_INTEREST = COUMPOUNDINGS * 100;
        String errorMessage = "Please enter a positive number for all required fields"
                + "\nLoan amount must be in reange (0, " + MAX_AMOUNT + "]"
                + "\nInterest rate must be  in range [0, " + MAX_INTEREST_RATE + "]"
                + "\nYears must be in range [0, " + MAX_INTEREST_RATE + "]";
        
        counter++;
        CounterJTextField.setText(String.valueOf(counter));
        
        //get inputs
        double amount = Double.parseDouble(PrincipalJTextField.getText());
        double rate = Double.parseDouble(RateJTextField.getText());
        double years = Double.parseDouble(YearsJTextField.getText());
        
        //calculate paymets using formula
        double payment = (amount * rate/PERIOD_INTEREST)/
                (1 - Math.pow((1 + rate/PERIOD_INTEREST),
                        years * (-COUMPOUNDINGS)));
        double interest = years * COUMPOUNDINGS * payment - amount;
        
        //displays results
        DecimalFormat dollars = new DecimalFormat("$#,##0.00");

        PaymentJTextField.setText(dollars.format(payment));
        InterestJTextField.setText(dollars.format(interest));
        
    }                                                

 /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Method            main()
 * Description       Calculates monthly payment. Relies on two
 *                   member methods inputDouble and payment
 * @param            args are the command line strings
 * @author           Caitlin McMurchie
 * Date              1/8/2018
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/ 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton CalculateJButton;
    private javax.swing.JButton ClearJButton;
    private javax.swing.JLabel CounterJLabel;
    private javax.swing.JTextField CounterJTextField;
    private javax.swing.JLabel InterestJLabel;
    private javax.swing.JTextField InterestJTextField;
    private javax.swing.JTextField PaymentJTextField;
    private javax.swing.JTextField PrincipalJTextField;
    private javax.swing.JLabel PrincipalLabel;
    private javax.swing.JButton QuitJButton;
    private javax.swing.JLabel RateJLabel;
    private javax.swing.JTextField RateJTextField;
    private javax.swing.JLabel YearsJLabel;
    private javax.swing.JTextField YearsJTextField;
    // End of variables declaration                   
}
